#!/bin/bash

sudo apt update
sudo apt upgrade

#installer lib mariadb
sudo apt install mariadb-server
sudo apt install libmariadb-dev
sudo apt-get install build-essential
sudo apt install libmysqlclient-dev
sudo apt install default-libmysqlclient-dev

#installer gtk
sudo apt-get install libgtk-3-dev

#installer harupdf
sudo apt install libhpdf-dev

#installer curl
sudo apt install curl
sudo apt install libboost-regex-dev
sudo apt install libcurl4-gnutls-dev
