-- CREATE DATABASE 2vine_ki_C;
-- USE 2vine_ki_C;
-- CREATE USER 'usr'@'localhost' IDENTIFIED BY 'mdp';
-- GRANT ALL PRIVILEGES ON * . * TO 'usr'@'localhost';
-- FLUSH PRIVILEGES;
CREATE TABLE ENTREPRISE(  ID INTEGER  AUTO_INCREMENT,  Nom VARCHAR(255), Lien VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE TRAVAIL( ID INTEGER AUTO_INCREMENT, Domaine VARCHAR(255),PRIMARY KEY (ID));

CREATE TABLE AGE(  ID INTEGER AUTO_INCREMENT,  Age_min INTEGER,  Age_max INTEGER, PRIMARY KEY (ID));

CREATE TABLE PHYSIQUE(  ID INTEGER AUTO_INCREMENT,  Taille_min DOUBLE,  Taille_max DOUBLE,  Genre CHAR(1),PRIMARY KEY (ID));

CREATE TABLE VISAGE( ID INTEGER AUTO_INCREMENT, Couleur_yeux VARCHAR(25), Couleur_cheveux VARCHAR(25), Taille_cheveux VARCHAR(25), Barbe CHAR(1), Moustache CHAR(1), Taille_barbe VARCHAR(25), Taille_moustache VARCHAR(25), Couleur_barbe VARCHAR(25), Couleur_moustache VARCHAR(25), PRIMARY KEY (ID));

CREATE TABLE EMPLOYE(  ID INTEGER AUTO_INCREMENT,  Nom VARCHAR(255),  Prenom VARCHAR(255),  Image VARCHAR(255),  ID_ENTREPRISE INTEGER,  ID_TRAVAIL INTEGER, ID_VISAGE INTEGER,  ID_AGE INTEGER,  ID_PHYSIQUE INTEGER, PRIMARY KEY (ID));

CREATE TABLE QUESTIONS(  ID INTEGER AUTO_INCREMENT,  Nom VARCHAR(255),  Prenom VARCHAR(255),  Image VARCHAR(255),  ID_EMPLOYE INTEGER,  ID_TRAVAIL INTEGER,  ID_VISAGE INTEGER,  ID_AGE INTEGER,  ID_PHYSIQUE INTEGER, PRIMARY KEY (ID));

CREATE TABLE FICHIER(  ID INTEGER AUTO_INCREMENT,  Nom VARCHAR(255),  Date_modif DATE,  ID_EMPLOYE INTEGER,PRIMARY KEY (ID));


ALTER TABLE EMPLOYE ADD FOREIGN KEY (ID_ENTREPRISE) REFERENCES ENTREPRISE(ID);
ALTER TABLE EMPLOYE ADD FOREIGN KEY (ID_TRAVAIL) REFERENCES TRAVAIL(ID);
ALTER TABLE EMPLOYE ADD FOREIGN KEY (ID_VISAGE) REFERENCES VISAGE(ID);
ALTER TABLE EMPLOYE ADD FOREIGN KEY (ID_AGE) REFERENCES AGE(ID);
ALTER TABLE EMPLOYE ADD FOREIGN KEY (ID_PHYSIQUE) REFERENCES PHYSIQUE(ID);

ALTER TABLE QUESTIONS ADD FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYE(ID);
ALTER TABLE QUESTIONS ADD FOREIGN KEY (ID_TRAVAIL) REFERENCES TRAVAIL(ID);
ALTER TABLE QUESTIONS ADD FOREIGN KEY (ID_VISAGE) REFERENCES VISAGE(ID);
ALTER TABLE QUESTIONS ADD FOREIGN KEY (ID_AGE) REFERENCES AGE(ID);
ALTER TABLE QUESTIONS ADD FOREIGN KEY (ID_PHYSIQUE) REFERENCES PHYSIQUE(ID);

ALTER TABLE FICHIER ADD FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYE(ID);
